# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install fftw
      run: |
          sudo -H apt update -y
          sudo -H apt install -y libfftw3-dev

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install -U -r requirements.txt
          pip install .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --max-line-length=88 --extend-ignore=E203 fpfs
    - name: Test with pytest
      run: |
        pytest -vv
